//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratorio_14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public string codcur { get; set; }
        public string nomcur { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> n_cuota { get; set; }
    }
}
