//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratorio_14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public string semestre { get; set; }
        public string codalu { get; set; }
        public string codcur { get; set; }
        public Nullable<int> pp { get; set; }
        public Nullable<int> pt { get; set; }
        public Nullable<int> ex { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fec_mat { get; set; }
        public Nullable<System.DateTime> fec_nota { get; set; }
    }
}
